### PR TITLE
Add menu entry for respawn-pane

### PR DESCRIPTION
**Pull request by giddie**
I found this: https://unix.stackexchange.com/questions/88392/is-there-an-easy-way-to-restart-a-tmux-pane

And thought it would be handy to have a menu item for that. Any thoughts?

### CODE REVIEW

**Comment by jaclu** [comment]
Great Idea!

**Comment by jaclu** [comment]
I'm not an expert on GitHub, but how come you didn't show up lower right as a Contributor? It's a practical way of giving credit to those who help out!
Something I did, or do you have a setting stating you don't want to be mentioned?

**Comment by jaclu** [comment]
If it is not solvable I could always list you in the ReadMe if that is to your preference Either way I really want to credit anybody contributing.

**Comment by giddie** [comment]
Well spotted! It turns out I hadn't yet verified the e-mail I used for that commit with Github, so it hadn't linked it to my account. The commit seems to link correctly to my account now, so I guess I may appear on the contributors list after some cache expires. Kind of you to think of attribution, even though it's an incredibly minor contribution!

**Comment by jaclu** [comment]
It never showed up, so I added a blurb in the Readme instead.
Credit should be given, otherwise what's the point in sending in a fix suggestion...

**Pull request merged**
